import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Typography, Button, Grid, useMediaQuery } from "@mui/material";
import { useTheme } from "@mui/material/styles";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { getSession } from "next-auth/react";
export default function Home() {
  const theme = useTheme();
  const router = useRouter();
  useEffect(() => {
    initState();
  }, []);
  const initState = async () => {
    const mysession = await getSession();
    console.log(mysession);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "space-between",
          marginTop: "24px",
        }}
      >
        <Typography fontWeight={"bold"} variant="h6">
          PESEvents
        </Typography>
      </div>
      <Grid container>
        <Grid
          item
          md={6}
          xs={12}
          style={{ position: "relative", height: "720px" }}
        >
          <Image src="/landing.png" layout="fill"></Image>
        </Grid>
        <Grid item md={6} xs={12}>
          <div
            style={
              useMediaQuery(theme.breakpoints.up("md"))
                ? {
                    display: "flex",
                    flexDirection: "column",
                    height: "720px",
                    justifyContent: "center",
                  }
                : {
                    display: "flex",
                    flexDirection: "column",
                    marginBottom: "48px",
                  }
            }
          >
            <Typography fontWeight={"bold"} variant="h3">
              All Events in one Place
            </Typography>
            <Typography
              style={{ marginBottom: "24px", marginTop: "24px" }}
              color="#78909c"
            >
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum.
            </Typography>
            <div style={{ display: "flex", justifyContent: "center" }}>
              <Button
                variant="contained"
                style={{ marginRight: "15px" }}
                onClick={() => {
                  router.push("/auth/student");
                }}
              >
                Sign Up/Login as A Student
              </Button>
              <Button
                variant="contained"
                onClick={() => {
                  router.push("/auth/clubhead");
                }}
              >
                Sign Up/Login as A Club Head
              </Button>
            </div>
          </div>
        </Grid>
      </Grid>
    </div>
  );
}
